### ISSUE TITLE
How to use zig-network?

### ISSUE THREAD

**Issue by tisonkun** [MasterQ32/zig-network#42]
I'm going to use zig-network for prototyping web application. But I'm unfamiliar how zig projects depend on libraries and the README.md file doesn't talk about it.

@MasterQ32 could you show an example to add a dependency or I must copy the source and link it manually?

**Comment by MasterQ32** [comment]
Check out the build.zig to see a usage example:

https://github.com/MasterQ32/zig-network/blob/bb77ec3469535967651f41c6ea260e357cce73d7/build.zig#L19-L22

Typically, people use either gyro or zigmod as a package manager, or just use git submodules for depending on other packages right now. You can also always just copy the source

**Comment by tisonkun** [comment]
Thank you!
