### ISSUE TITLE
SO_BROADCAST setsockopt for UDP socket

### ISSUE THREAD

**Issue by twystd** [MasterQ32/zig-network#52]
Hi,

Any possibility of adding a `setBroadcast` function to enable/disable the `SO_BROADCAST` socket option (required for UDP sockets to send broadcast messages) ? The code looks something like this:
```
    /// Set SO_BROADCAST sockopt
    pub fn setBroadcast(self: *Self, enable: bool) !void {
        const val: u32 = if (enable)  1 else 0;
        if (is_windows) {
            try windows.setsockopt(self.internal, std.os.SOL.SOCKET, std.os.SO.BROADCAST, std.mem.asBytes(&val));
        } else {
            try std.os.setsockopt(self.internal, std.os.SOL.SOCKET, std.os.SO.BROADCAST, std.mem.asBytes(&val));
        }
    }
```

_(I can do a pull request if you like but it seemed like such a small thing)_

**Comment by MasterQ32** [comment]
Hm. I left broadcasts out on purpose, as new software shouldnt use them, as they are not compatible to IPv6. 

But i could see some use cases, what are yours?

Feel free to make a PR tho, if you have a use case for it. But please make a comment about the missing support for IPv6 and maybe assert an IPv4 socket

**Comment by twystd** [comment]
Thought there might be a reason :-). This particular use case is adding a [zig language binding](https://github.com/uhppoted/uhppoted-codegen/tree/main/bindings/zig) to an interface to some legacy hardware that uses UDP broadcast for device discovery.

I'll work up your suggestions and submit a PR - thanks!

**Comment by twystd** [comment]
Cool! Thanks!
