### ISSUE TITLE
SocketSet.deinit frees memory with wrong alignment on Windows

### ISSUE THREAD

**Issue by zeroZshadow** [MasterQ32/zig-network#62]
On windows, the following step in `deinit` is problematic due to an alignment mismatch (1 instead of 8)

`self.read_fd_set.deinit(self.allocator)`

The cause is due to `memSlice` in `allocator.free(self.memSlice());` not setting the alignment when casting pointer type.

**Comment by Weldify** [comment]
@zeroZshadow The latest PR should have fixed this

**Comment by mochalins** [comment]
I believe this can be closed now @zeroZshadow @MasterQ32
