### ISSUE TITLE
Support for Sending Ethernet Frames

### ISSUE THREAD

**Issue by sectasy0** [MasterQ32/zig-network#73]
Hey there, folks! I'm looking for a way to send ethernet frames in Zig, does this library support that?

**Comment by MasterQ32** [comment]
No, this is out of scope for `zig-network`. Ethernet frames are part of a network driver, but raw sockets are not really well supported anywhere.

Depending on your use case, TUN/TAP on Linux might be the right choice for you, or WinPCAP on windows
